//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scenes/Assets/Input Manager/MyInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MyInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MyInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyInputActions"",
    ""maps"": [
        {
            ""name"": ""AfterLifeActions"",
            ""id"": ""e22426b3-a528-4345-a6d8-c83d443aa0d8"",
            ""actions"": [
                {
                    ""name"": ""MoveView"",
                    ""type"": ""Value"",
                    ""id"": ""b12eb0ce-2732-43ef-a4d5-442b951d3350"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2,AxisDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateView"",
                    ""type"": ""Button"",
                    ""id"": ""4ff96c13-0f82-405c-826b-f05b7e5f6b31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleTopDownView"",
                    ""type"": ""Button"",
                    ""id"": ""997e7fbf-d18a-4b8b-9043-44d52aed8039"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""e42ac842-f7c6-4793-b1a9-41ce7ae1b4ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadGame"",
                    ""type"": ""Button"",
                    ""id"": ""739b8b1f-9892-4055-aec5-102e4b07a6bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadScenario"",
                    ""type"": ""Button"",
                    ""id"": ""4f1f875a-ec7a-4248-a52e-58ae99389ef4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SaveGame"",
                    ""type"": ""Button"",
                    ""id"": ""0a0ce2ca-e10f-4c00-8969-81c17dcd5369"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""a770b067-38a8-43ef-b3d7-54f332bc0c00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AudioMenu"",
                    ""type"": ""Button"",
                    ""id"": ""ad4e8233-e3ec-4a75-a505-6fc5431863d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NewGame"",
                    ""type"": ""Button"",
                    ""id"": ""cc18a366-a750-4e7c-ba45-b535ecc2d3b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseMenuOrPopUp"",
                    ""type"": ""Button"",
                    ""id"": ""f1bd62b6-cdbf-4b30-96d6-383b37421942"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ports"",
                    ""type"": ""Button"",
                    ""id"": ""f7db2ba9-1a8f-4584-b8a4-b752e437021e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Topias"",
                    ""type"": ""Button"",
                    ""id"": ""067bddbc-f067-4113-a1c1-55b414948288"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraphView"",
                    ""type"": ""Button"",
                    ""id"": ""c0e4dc34-5c87-4c3c-9030-04f6dd8fa0f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateMiscZoning"",
                    ""type"": ""Button"",
                    ""id"": ""28a75c9b-9dbd-47ce-9a02-78933f578caf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleMapView"",
                    ""type"": ""Button"",
                    ""id"": ""c9261124-994d-441c-8810-daa79b07075f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gates"",
                    ""type"": ""Button"",
                    ""id"": ""779d48ad-c702-45f0-b0f6-1b7d9d88a866"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleHelpers"",
                    ""type"": ""Button"",
                    ""id"": ""d2fbd553-afa3-4338-a6aa-a2349d882d1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SOULView"",
                    ""type"": ""Button"",
                    ""id"": ""d39374df-1a2d-47a4-ad0a-f53b4b1c90c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateKarmaZoning"",
                    ""type"": ""Button"",
                    ""id"": ""29b2cdc9-1d65-4912-8e2d-0989abcac660"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateLimboZoning"",
                    ""type"": ""Button"",
                    ""id"": ""cf999356-4dbf-49eb-beb1-9cddb5420e2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MicroView"",
                    ""type"": ""Button"",
                    ""id"": ""a456d4fe-0caf-4916-973b-6ee2db54564d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrainingCentres"",
                    ""type"": ""Button"",
                    ""id"": ""df0e0f2f-140b-4acc-bdfc-63dcde2c197a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateOmniBolgeLoveDomeZoning"",
                    ""type"": ""Button"",
                    ""id"": ""bdd964c8-6980-4bd5-8fef-755fbf494ff5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TogglePlanetView"",
                    ""type"": ""Button"",
                    ""id"": ""73646390-85d1-46a7-8962-cb29ccaa75c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roads"",
                    ""type"": ""Button"",
                    ""id"": ""006c9eed-cd4f-4ac0-a4bf-8cae251de72a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""3ee33888-3e2b-4d5c-a051-eb022d6ecb09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KarmaTrack"",
                    ""type"": ""Button"",
                    ""id"": ""fc70c8f0-83d2-4941-b6fa-bb91a75f110a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleMicroManager"",
                    ""type"": ""Button"",
                    ""id"": ""b206c619-bc5b-4052-bb24-290f4f99b666"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NukeButton"",
                    ""type"": ""Button"",
                    ""id"": ""c51c4bbd-995f-4783-abdb-6625ff1c0eb9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleRemoteControl"",
                    ""type"": ""Button"",
                    ""id"": ""726b3364-25c5-4fe7-a662-e28d9b82ae4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TogglePreviousTempo"",
                    ""type"": ""Button"",
                    ""id"": ""f13ee301-9347-4394-90e1-f86cba223e34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GreenZoning"",
                    ""type"": ""Button"",
                    ""id"": ""2f09239c-0755-42fd-8b5b-2ef3f810ca08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""YellowZoning"",
                    ""type"": ""Button"",
                    ""id"": ""a087673e-424f-4b5b-8bd7-30c22dc2e75b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OrangeZoning"",
                    ""type"": ""Button"",
                    ""id"": ""ef24dbe8-d224-4db6-ae5a-de6ca365ced0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BrownZoning"",
                    ""type"": ""Button"",
                    ""id"": ""2c860b02-f885-40b5-9ed5-0929d5c81e23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PurpleZoning"",
                    ""type"": ""Button"",
                    ""id"": ""5aa13462-8e6e-48e5-a26a-be4c41202e2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RedZoning"",
                    ""type"": ""Button"",
                    ""id"": ""7493fd67-b9a1-4a62-a64b-df3814ee548e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BlueZoning"",
                    ""type"": ""Button"",
                    ""id"": ""00738cfe-6edf-46f3-bd8b-1fa2f7f76181"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericZoning"",
                    ""type"": ""Button"",
                    ""id"": ""506d78f4-76a7-47fc-ab95-1798a3072926"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""03f7f7db-6a94-45cc-9ff7-be3ea335cadf"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JumpViewToHeaven"",
                    ""type"": ""Button"",
                    ""id"": ""a354a6fb-2ce9-4ba5-90a6-cd757e626d8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpViewToHell"",
                    ""type"": ""Button"",
                    ""id"": ""7acf63ab-d669-42a1-bf2e-5e5a7747feb6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CenterANDZoomIn"",
                    ""type"": ""Button"",
                    ""id"": ""d8c1bca4-90a8-4e0a-aa76-8f5d376fec94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CenterANDZoomOut"",
                    ""type"": ""Button"",
                    ""id"": ""1553b178-ccbf-4d60-a4f2-21712c809218"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CentreViewToCursor"",
                    ""type"": ""Button"",
                    ""id"": ""d7c99452-c5d6-4e93-8718-4b359980067f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector - Keyboard"",
                    ""id"": ""f0a3a2e9-1f77-4fb8-9e5b-2f62ab33c580"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveView"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c7420d5e-4a00-4496-a063-d764c82b9b10"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4f54dcae-5c41-4f99-a9ec-aa7a0de83a8c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""fd201676-5f99-4c69-91c1-4013343783a7"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""87578ab0-d667-465b-973d-ccf3c4448a47"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""372e01a6-0c82-44fd-9f9b-abbddac6c0dd"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis - Keyboard"",
                    ""id"": ""6d57abca-da8a-49d8-aa0c-c5c7bd7bb466"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""cdeb8d19-795a-480d-b1ca-29c60cbca54d"",
                    ""path"": ""<Keyboard>/leftBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b7615f5c-6595-48d0-b7b8-2e2b13313d60"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis - Controller"",
                    ""id"": ""bc78b0bc-d4c7-49b7-9911-a00d5031eff7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1f551c80-1ed2-4dcc-bc47-44daa81889bf"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""174fee25-2c52-4d44-8649-c2ff26de65fb"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b918ed03-3254-424c-9706-ba3e8e7be12d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleTopDownView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f304610-0f36-4b59-9142-58be153eb265"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleTopDownView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75ba7052-a605-4992-ac6c-ffa523334b8c"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9beb037e-e0ca-40b1-8b45-89c22f092821"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8716818-39ce-4a4f-8345-b477d0a49247"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadScenario"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""deb863a7-9d93-4b10-b4b5-a1480fa30e3c"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaveGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f217bc57-f311-4b31-b265-169dd6af907e"",
                    ""path"": ""<Keyboard>/f8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a0a0a16-93d6-4bb3-beeb-406bfc838aac"",
                    ""path"": ""<Keyboard>/f9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AudioMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b557b51-3ea4-4bc5-aa0c-3b43b593a225"",
                    ""path"": ""<Keyboard>/f10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NewGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00bcf683-ad98-40b3-9b8a-b80c767a290a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMenuOrPopUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31764cd3-19e3-48e9-b264-ffcf7820220d"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ports"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14e6ae3e-bc4b-4c1e-bdd3-5c8b8461876d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Topias"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0695a58-0e30-4b15-99c2-605baee5f8b1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraphView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21520446-cb63-4815-ac8b-46d0c8524a6d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateMiscZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f6f8e10-9401-4a84-8750-ee8abc86c311"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMapView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd35125d-9c36-4fdd-ba55-7a927d19e343"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gates"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3dc0383-bf6b-4a07-a5f2-7d0fe6c8bcca"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleHelpers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c0dc3f0-8b3d-4d09-a96e-856bbcfcd85b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SOULView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68bd2a1e-8524-418c-a1ec-5f8140cbbb39"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateKarmaZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b6130b9-725b-4eb8-b47e-49aaf1cfe4f4"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateLimboZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06ed70bc-ca3d-4224-8d9d-3574e0de3d77"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MicroView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1141bf6-e47b-48b9-9f5a-aefc8612f6cf"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrainingCentres"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c433caf0-919e-4b67-a640-c51d75a97da1"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateOmniBolgeLoveDomeZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9cce79e-8615-41f9-9d87-6b2b91c46b2e"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TogglePlanetView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afd1ea5e-8d53-45f4-959f-f2b754c3e218"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roads"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d981da5-8530-4a3f-8d9d-c8268ba336f3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""372b64fb-9fd0-4e55-95d6-6beca89e16e1"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KarmaTrack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce206c9c-5920-4d3c-beee-fa6963b14656"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMicroManager"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd9449d9-b8de-41b9-b5e4-7fcf6a3db1c4"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NukeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28afa276-dce9-48c2-85bb-d95c0f362ad3"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleRemoteControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c768927-501f-4653-bf0d-83def33b4e61"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TogglePreviousTempo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""667367c6-2d2a-4163-b95f-5fb8e626c723"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GreenZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af78bb23-8475-4246-a3ce-4b0e2f45cdfe"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YellowZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29e1df01-6835-447c-8b1d-8cb19b0f81e8"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrangeZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d31aac4-d1ba-458d-bc16-df98ff5d9970"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BrownZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5494195-c27c-404b-8b2c-02774e159d5a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PurpleZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85b4cbd4-4c11-4aba-9583-51ae48639ea7"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RedZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db3f6d63-bdc1-4e39-ae6b-65fdbfb40651"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BlueZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a2eba60-bd91-450a-acfd-5e27451ff6ee"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericZoning"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96038aa5-c967-4da4-bbdb-d48f68ca45f3"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9afd7443-4638-45dc-bcf4-aa0b3445a5bb"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""65e93222-45eb-4f7f-ad78-c8ceb76862fa"",
                    ""path"": ""<Keyboard>/equals"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d60cde62-a471-4eee-8b61-0374a052324c"",
                    ""path"": ""<Keyboard>/pageUp"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpViewToHeaven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2ff4091-235e-430d-b766-62951935db83"",
                    ""path"": ""<Keyboard>/pageDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpViewToHell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""534d9fb8-5604-452f-9337-ae99ff0f631f"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterANDZoomIn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d95824f5-3ebb-4155-a6e4-a1583d86fb36"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterANDZoomIn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""bfb0a604-d2c7-4ce6-8e85-1ce85a53f050"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterANDZoomIn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""e6495dd2-2057-418e-a0a1-273d00a46c9c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterANDZoomOut"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""500f5bb8-8ef9-4855-8330-f4ac8983080b"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterANDZoomOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""850ef1cb-660d-48a5-9a9d-f114f94e79bf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterANDZoomOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8167c46b-bd55-41b5-b28c-10ebb7beb7e0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CentreViewToCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // AfterLifeActions
        m_AfterLifeActions = asset.FindActionMap("AfterLifeActions", throwIfNotFound: true);
        m_AfterLifeActions_MoveView = m_AfterLifeActions.FindAction("MoveView", throwIfNotFound: true);
        m_AfterLifeActions_RotateView = m_AfterLifeActions.FindAction("RotateView", throwIfNotFound: true);
        m_AfterLifeActions_ToggleTopDownView = m_AfterLifeActions.FindAction("ToggleTopDownView", throwIfNotFound: true);
        m_AfterLifeActions_Pause = m_AfterLifeActions.FindAction("Pause", throwIfNotFound: true);
        m_AfterLifeActions_LoadGame = m_AfterLifeActions.FindAction("LoadGame", throwIfNotFound: true);
        m_AfterLifeActions_LoadScenario = m_AfterLifeActions.FindAction("LoadScenario", throwIfNotFound: true);
        m_AfterLifeActions_SaveGame = m_AfterLifeActions.FindAction("SaveGame", throwIfNotFound: true);
        m_AfterLifeActions_Quit = m_AfterLifeActions.FindAction("Quit", throwIfNotFound: true);
        m_AfterLifeActions_AudioMenu = m_AfterLifeActions.FindAction("AudioMenu", throwIfNotFound: true);
        m_AfterLifeActions_NewGame = m_AfterLifeActions.FindAction("NewGame", throwIfNotFound: true);
        m_AfterLifeActions_CloseMenuOrPopUp = m_AfterLifeActions.FindAction("CloseMenuOrPopUp", throwIfNotFound: true);
        m_AfterLifeActions_Ports = m_AfterLifeActions.FindAction("Ports", throwIfNotFound: true);
        m_AfterLifeActions_Topias = m_AfterLifeActions.FindAction("Topias", throwIfNotFound: true);
        m_AfterLifeActions_GraphView = m_AfterLifeActions.FindAction("GraphView", throwIfNotFound: true);
        m_AfterLifeActions_ActivateMiscZoning = m_AfterLifeActions.FindAction("ActivateMiscZoning", throwIfNotFound: true);
        m_AfterLifeActions_ToggleMapView = m_AfterLifeActions.FindAction("ToggleMapView", throwIfNotFound: true);
        m_AfterLifeActions_Gates = m_AfterLifeActions.FindAction("Gates", throwIfNotFound: true);
        m_AfterLifeActions_ToggleHelpers = m_AfterLifeActions.FindAction("ToggleHelpers", throwIfNotFound: true);
        m_AfterLifeActions_SOULView = m_AfterLifeActions.FindAction("SOULView", throwIfNotFound: true);
        m_AfterLifeActions_ActivateKarmaZoning = m_AfterLifeActions.FindAction("ActivateKarmaZoning", throwIfNotFound: true);
        m_AfterLifeActions_ActivateLimboZoning = m_AfterLifeActions.FindAction("ActivateLimboZoning", throwIfNotFound: true);
        m_AfterLifeActions_MicroView = m_AfterLifeActions.FindAction("MicroView", throwIfNotFound: true);
        m_AfterLifeActions_TrainingCentres = m_AfterLifeActions.FindAction("TrainingCentres", throwIfNotFound: true);
        m_AfterLifeActions_ActivateOmniBolgeLoveDomeZoning = m_AfterLifeActions.FindAction("ActivateOmniBolgeLoveDomeZoning", throwIfNotFound: true);
        m_AfterLifeActions_TogglePlanetView = m_AfterLifeActions.FindAction("TogglePlanetView", throwIfNotFound: true);
        m_AfterLifeActions_Roads = m_AfterLifeActions.FindAction("Roads", throwIfNotFound: true);
        m_AfterLifeActions_SpecialBuildings = m_AfterLifeActions.FindAction("SpecialBuildings", throwIfNotFound: true);
        m_AfterLifeActions_KarmaTrack = m_AfterLifeActions.FindAction("KarmaTrack", throwIfNotFound: true);
        m_AfterLifeActions_ToggleMicroManager = m_AfterLifeActions.FindAction("ToggleMicroManager", throwIfNotFound: true);
        m_AfterLifeActions_NukeButton = m_AfterLifeActions.FindAction("NukeButton", throwIfNotFound: true);
        m_AfterLifeActions_ToggleRemoteControl = m_AfterLifeActions.FindAction("ToggleRemoteControl", throwIfNotFound: true);
        m_AfterLifeActions_TogglePreviousTempo = m_AfterLifeActions.FindAction("TogglePreviousTempo", throwIfNotFound: true);
        m_AfterLifeActions_GreenZoning = m_AfterLifeActions.FindAction("GreenZoning", throwIfNotFound: true);
        m_AfterLifeActions_YellowZoning = m_AfterLifeActions.FindAction("YellowZoning", throwIfNotFound: true);
        m_AfterLifeActions_OrangeZoning = m_AfterLifeActions.FindAction("OrangeZoning", throwIfNotFound: true);
        m_AfterLifeActions_BrownZoning = m_AfterLifeActions.FindAction("BrownZoning", throwIfNotFound: true);
        m_AfterLifeActions_PurpleZoning = m_AfterLifeActions.FindAction("PurpleZoning", throwIfNotFound: true);
        m_AfterLifeActions_RedZoning = m_AfterLifeActions.FindAction("RedZoning", throwIfNotFound: true);
        m_AfterLifeActions_BlueZoning = m_AfterLifeActions.FindAction("BlueZoning", throwIfNotFound: true);
        m_AfterLifeActions_GenericZoning = m_AfterLifeActions.FindAction("GenericZoning", throwIfNotFound: true);
        m_AfterLifeActions_Zoom = m_AfterLifeActions.FindAction("Zoom", throwIfNotFound: true);
        m_AfterLifeActions_JumpViewToHeaven = m_AfterLifeActions.FindAction("JumpViewToHeaven", throwIfNotFound: true);
        m_AfterLifeActions_JumpViewToHell = m_AfterLifeActions.FindAction("JumpViewToHell", throwIfNotFound: true);
        m_AfterLifeActions_CenterANDZoomIn = m_AfterLifeActions.FindAction("CenterANDZoomIn", throwIfNotFound: true);
        m_AfterLifeActions_CenterANDZoomOut = m_AfterLifeActions.FindAction("CenterANDZoomOut", throwIfNotFound: true);
        m_AfterLifeActions_CentreViewToCursor = m_AfterLifeActions.FindAction("CentreViewToCursor", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // AfterLifeActions
    private readonly InputActionMap m_AfterLifeActions;
    private IAfterLifeActionsActions m_AfterLifeActionsActionsCallbackInterface;
    private readonly InputAction m_AfterLifeActions_MoveView;
    private readonly InputAction m_AfterLifeActions_RotateView;
    private readonly InputAction m_AfterLifeActions_ToggleTopDownView;
    private readonly InputAction m_AfterLifeActions_Pause;
    private readonly InputAction m_AfterLifeActions_LoadGame;
    private readonly InputAction m_AfterLifeActions_LoadScenario;
    private readonly InputAction m_AfterLifeActions_SaveGame;
    private readonly InputAction m_AfterLifeActions_Quit;
    private readonly InputAction m_AfterLifeActions_AudioMenu;
    private readonly InputAction m_AfterLifeActions_NewGame;
    private readonly InputAction m_AfterLifeActions_CloseMenuOrPopUp;
    private readonly InputAction m_AfterLifeActions_Ports;
    private readonly InputAction m_AfterLifeActions_Topias;
    private readonly InputAction m_AfterLifeActions_GraphView;
    private readonly InputAction m_AfterLifeActions_ActivateMiscZoning;
    private readonly InputAction m_AfterLifeActions_ToggleMapView;
    private readonly InputAction m_AfterLifeActions_Gates;
    private readonly InputAction m_AfterLifeActions_ToggleHelpers;
    private readonly InputAction m_AfterLifeActions_SOULView;
    private readonly InputAction m_AfterLifeActions_ActivateKarmaZoning;
    private readonly InputAction m_AfterLifeActions_ActivateLimboZoning;
    private readonly InputAction m_AfterLifeActions_MicroView;
    private readonly InputAction m_AfterLifeActions_TrainingCentres;
    private readonly InputAction m_AfterLifeActions_ActivateOmniBolgeLoveDomeZoning;
    private readonly InputAction m_AfterLifeActions_TogglePlanetView;
    private readonly InputAction m_AfterLifeActions_Roads;
    private readonly InputAction m_AfterLifeActions_SpecialBuildings;
    private readonly InputAction m_AfterLifeActions_KarmaTrack;
    private readonly InputAction m_AfterLifeActions_ToggleMicroManager;
    private readonly InputAction m_AfterLifeActions_NukeButton;
    private readonly InputAction m_AfterLifeActions_ToggleRemoteControl;
    private readonly InputAction m_AfterLifeActions_TogglePreviousTempo;
    private readonly InputAction m_AfterLifeActions_GreenZoning;
    private readonly InputAction m_AfterLifeActions_YellowZoning;
    private readonly InputAction m_AfterLifeActions_OrangeZoning;
    private readonly InputAction m_AfterLifeActions_BrownZoning;
    private readonly InputAction m_AfterLifeActions_PurpleZoning;
    private readonly InputAction m_AfterLifeActions_RedZoning;
    private readonly InputAction m_AfterLifeActions_BlueZoning;
    private readonly InputAction m_AfterLifeActions_GenericZoning;
    private readonly InputAction m_AfterLifeActions_Zoom;
    private readonly InputAction m_AfterLifeActions_JumpViewToHeaven;
    private readonly InputAction m_AfterLifeActions_JumpViewToHell;
    private readonly InputAction m_AfterLifeActions_CenterANDZoomIn;
    private readonly InputAction m_AfterLifeActions_CenterANDZoomOut;
    private readonly InputAction m_AfterLifeActions_CentreViewToCursor;
    public struct AfterLifeActionsActions
    {
        private @MyInputActions m_Wrapper;
        public AfterLifeActionsActions(@MyInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveView => m_Wrapper.m_AfterLifeActions_MoveView;
        public InputAction @RotateView => m_Wrapper.m_AfterLifeActions_RotateView;
        public InputAction @ToggleTopDownView => m_Wrapper.m_AfterLifeActions_ToggleTopDownView;
        public InputAction @Pause => m_Wrapper.m_AfterLifeActions_Pause;
        public InputAction @LoadGame => m_Wrapper.m_AfterLifeActions_LoadGame;
        public InputAction @LoadScenario => m_Wrapper.m_AfterLifeActions_LoadScenario;
        public InputAction @SaveGame => m_Wrapper.m_AfterLifeActions_SaveGame;
        public InputAction @Quit => m_Wrapper.m_AfterLifeActions_Quit;
        public InputAction @AudioMenu => m_Wrapper.m_AfterLifeActions_AudioMenu;
        public InputAction @NewGame => m_Wrapper.m_AfterLifeActions_NewGame;
        public InputAction @CloseMenuOrPopUp => m_Wrapper.m_AfterLifeActions_CloseMenuOrPopUp;
        public InputAction @Ports => m_Wrapper.m_AfterLifeActions_Ports;
        public InputAction @Topias => m_Wrapper.m_AfterLifeActions_Topias;
        public InputAction @GraphView => m_Wrapper.m_AfterLifeActions_GraphView;
        public InputAction @ActivateMiscZoning => m_Wrapper.m_AfterLifeActions_ActivateMiscZoning;
        public InputAction @ToggleMapView => m_Wrapper.m_AfterLifeActions_ToggleMapView;
        public InputAction @Gates => m_Wrapper.m_AfterLifeActions_Gates;
        public InputAction @ToggleHelpers => m_Wrapper.m_AfterLifeActions_ToggleHelpers;
        public InputAction @SOULView => m_Wrapper.m_AfterLifeActions_SOULView;
        public InputAction @ActivateKarmaZoning => m_Wrapper.m_AfterLifeActions_ActivateKarmaZoning;
        public InputAction @ActivateLimboZoning => m_Wrapper.m_AfterLifeActions_ActivateLimboZoning;
        public InputAction @MicroView => m_Wrapper.m_AfterLifeActions_MicroView;
        public InputAction @TrainingCentres => m_Wrapper.m_AfterLifeActions_TrainingCentres;
        public InputAction @ActivateOmniBolgeLoveDomeZoning => m_Wrapper.m_AfterLifeActions_ActivateOmniBolgeLoveDomeZoning;
        public InputAction @TogglePlanetView => m_Wrapper.m_AfterLifeActions_TogglePlanetView;
        public InputAction @Roads => m_Wrapper.m_AfterLifeActions_Roads;
        public InputAction @SpecialBuildings => m_Wrapper.m_AfterLifeActions_SpecialBuildings;
        public InputAction @KarmaTrack => m_Wrapper.m_AfterLifeActions_KarmaTrack;
        public InputAction @ToggleMicroManager => m_Wrapper.m_AfterLifeActions_ToggleMicroManager;
        public InputAction @NukeButton => m_Wrapper.m_AfterLifeActions_NukeButton;
        public InputAction @ToggleRemoteControl => m_Wrapper.m_AfterLifeActions_ToggleRemoteControl;
        public InputAction @TogglePreviousTempo => m_Wrapper.m_AfterLifeActions_TogglePreviousTempo;
        public InputAction @GreenZoning => m_Wrapper.m_AfterLifeActions_GreenZoning;
        public InputAction @YellowZoning => m_Wrapper.m_AfterLifeActions_YellowZoning;
        public InputAction @OrangeZoning => m_Wrapper.m_AfterLifeActions_OrangeZoning;
        public InputAction @BrownZoning => m_Wrapper.m_AfterLifeActions_BrownZoning;
        public InputAction @PurpleZoning => m_Wrapper.m_AfterLifeActions_PurpleZoning;
        public InputAction @RedZoning => m_Wrapper.m_AfterLifeActions_RedZoning;
        public InputAction @BlueZoning => m_Wrapper.m_AfterLifeActions_BlueZoning;
        public InputAction @GenericZoning => m_Wrapper.m_AfterLifeActions_GenericZoning;
        public InputAction @Zoom => m_Wrapper.m_AfterLifeActions_Zoom;
        public InputAction @JumpViewToHeaven => m_Wrapper.m_AfterLifeActions_JumpViewToHeaven;
        public InputAction @JumpViewToHell => m_Wrapper.m_AfterLifeActions_JumpViewToHell;
        public InputAction @CenterANDZoomIn => m_Wrapper.m_AfterLifeActions_CenterANDZoomIn;
        public InputAction @CenterANDZoomOut => m_Wrapper.m_AfterLifeActions_CenterANDZoomOut;
        public InputAction @CentreViewToCursor => m_Wrapper.m_AfterLifeActions_CentreViewToCursor;
        public InputActionMap Get() { return m_Wrapper.m_AfterLifeActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AfterLifeActionsActions set) { return set.Get(); }
        public void SetCallbacks(IAfterLifeActionsActions instance)
        {
            if (m_Wrapper.m_AfterLifeActionsActionsCallbackInterface != null)
            {
                @MoveView.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnMoveView;
                @MoveView.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnMoveView;
                @MoveView.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnMoveView;
                @RotateView.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnRotateView;
                @RotateView.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnRotateView;
                @RotateView.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnRotateView;
                @ToggleTopDownView.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleTopDownView;
                @ToggleTopDownView.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleTopDownView;
                @ToggleTopDownView.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleTopDownView;
                @Pause.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnPause;
                @LoadGame.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnLoadGame;
                @LoadGame.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnLoadGame;
                @LoadGame.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnLoadGame;
                @LoadScenario.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnLoadScenario;
                @LoadScenario.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnLoadScenario;
                @LoadScenario.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnLoadScenario;
                @SaveGame.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnSaveGame;
                @SaveGame.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnSaveGame;
                @SaveGame.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnSaveGame;
                @Quit.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnQuit;
                @Quit.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnQuit;
                @Quit.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnQuit;
                @AudioMenu.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnAudioMenu;
                @AudioMenu.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnAudioMenu;
                @AudioMenu.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnAudioMenu;
                @NewGame.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnNewGame;
                @NewGame.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnNewGame;
                @NewGame.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnNewGame;
                @CloseMenuOrPopUp.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCloseMenuOrPopUp;
                @CloseMenuOrPopUp.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCloseMenuOrPopUp;
                @CloseMenuOrPopUp.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCloseMenuOrPopUp;
                @Ports.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnPorts;
                @Ports.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnPorts;
                @Ports.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnPorts;
                @Topias.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTopias;
                @Topias.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTopias;
                @Topias.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTopias;
                @GraphView.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGraphView;
                @GraphView.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGraphView;
                @GraphView.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGraphView;
                @ActivateMiscZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateMiscZoning;
                @ActivateMiscZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateMiscZoning;
                @ActivateMiscZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateMiscZoning;
                @ToggleMapView.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleMapView;
                @ToggleMapView.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleMapView;
                @ToggleMapView.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleMapView;
                @Gates.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGates;
                @Gates.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGates;
                @Gates.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGates;
                @ToggleHelpers.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleHelpers;
                @ToggleHelpers.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleHelpers;
                @ToggleHelpers.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleHelpers;
                @SOULView.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnSOULView;
                @SOULView.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnSOULView;
                @SOULView.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnSOULView;
                @ActivateKarmaZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateKarmaZoning;
                @ActivateKarmaZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateKarmaZoning;
                @ActivateKarmaZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateKarmaZoning;
                @ActivateLimboZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateLimboZoning;
                @ActivateLimboZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateLimboZoning;
                @ActivateLimboZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateLimboZoning;
                @MicroView.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnMicroView;
                @MicroView.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnMicroView;
                @MicroView.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnMicroView;
                @TrainingCentres.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTrainingCentres;
                @TrainingCentres.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTrainingCentres;
                @TrainingCentres.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTrainingCentres;
                @ActivateOmniBolgeLoveDomeZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateOmniBolgeLoveDomeZoning;
                @ActivateOmniBolgeLoveDomeZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateOmniBolgeLoveDomeZoning;
                @ActivateOmniBolgeLoveDomeZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnActivateOmniBolgeLoveDomeZoning;
                @TogglePlanetView.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTogglePlanetView;
                @TogglePlanetView.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTogglePlanetView;
                @TogglePlanetView.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTogglePlanetView;
                @Roads.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnRoads;
                @Roads.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnRoads;
                @Roads.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnRoads;
                @SpecialBuildings.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnSpecialBuildings;
                @SpecialBuildings.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnSpecialBuildings;
                @SpecialBuildings.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnSpecialBuildings;
                @KarmaTrack.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnKarmaTrack;
                @KarmaTrack.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnKarmaTrack;
                @KarmaTrack.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnKarmaTrack;
                @ToggleMicroManager.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleMicroManager;
                @ToggleMicroManager.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleMicroManager;
                @ToggleMicroManager.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleMicroManager;
                @NukeButton.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnNukeButton;
                @NukeButton.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnNukeButton;
                @NukeButton.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnNukeButton;
                @ToggleRemoteControl.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleRemoteControl;
                @ToggleRemoteControl.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleRemoteControl;
                @ToggleRemoteControl.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnToggleRemoteControl;
                @TogglePreviousTempo.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTogglePreviousTempo;
                @TogglePreviousTempo.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTogglePreviousTempo;
                @TogglePreviousTempo.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnTogglePreviousTempo;
                @GreenZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGreenZoning;
                @GreenZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGreenZoning;
                @GreenZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGreenZoning;
                @YellowZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnYellowZoning;
                @YellowZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnYellowZoning;
                @YellowZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnYellowZoning;
                @OrangeZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnOrangeZoning;
                @OrangeZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnOrangeZoning;
                @OrangeZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnOrangeZoning;
                @BrownZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnBrownZoning;
                @BrownZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnBrownZoning;
                @BrownZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnBrownZoning;
                @PurpleZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnPurpleZoning;
                @PurpleZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnPurpleZoning;
                @PurpleZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnPurpleZoning;
                @RedZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnRedZoning;
                @RedZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnRedZoning;
                @RedZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnRedZoning;
                @BlueZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnBlueZoning;
                @BlueZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnBlueZoning;
                @BlueZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnBlueZoning;
                @GenericZoning.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGenericZoning;
                @GenericZoning.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGenericZoning;
                @GenericZoning.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnGenericZoning;
                @Zoom.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnZoom;
                @JumpViewToHeaven.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnJumpViewToHeaven;
                @JumpViewToHeaven.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnJumpViewToHeaven;
                @JumpViewToHeaven.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnJumpViewToHeaven;
                @JumpViewToHell.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnJumpViewToHell;
                @JumpViewToHell.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnJumpViewToHell;
                @JumpViewToHell.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnJumpViewToHell;
                @CenterANDZoomIn.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCenterANDZoomIn;
                @CenterANDZoomIn.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCenterANDZoomIn;
                @CenterANDZoomIn.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCenterANDZoomIn;
                @CenterANDZoomOut.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCenterANDZoomOut;
                @CenterANDZoomOut.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCenterANDZoomOut;
                @CenterANDZoomOut.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCenterANDZoomOut;
                @CentreViewToCursor.started -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCentreViewToCursor;
                @CentreViewToCursor.performed -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCentreViewToCursor;
                @CentreViewToCursor.canceled -= m_Wrapper.m_AfterLifeActionsActionsCallbackInterface.OnCentreViewToCursor;
            }
            m_Wrapper.m_AfterLifeActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveView.started += instance.OnMoveView;
                @MoveView.performed += instance.OnMoveView;
                @MoveView.canceled += instance.OnMoveView;
                @RotateView.started += instance.OnRotateView;
                @RotateView.performed += instance.OnRotateView;
                @RotateView.canceled += instance.OnRotateView;
                @ToggleTopDownView.started += instance.OnToggleTopDownView;
                @ToggleTopDownView.performed += instance.OnToggleTopDownView;
                @ToggleTopDownView.canceled += instance.OnToggleTopDownView;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @LoadGame.started += instance.OnLoadGame;
                @LoadGame.performed += instance.OnLoadGame;
                @LoadGame.canceled += instance.OnLoadGame;
                @LoadScenario.started += instance.OnLoadScenario;
                @LoadScenario.performed += instance.OnLoadScenario;
                @LoadScenario.canceled += instance.OnLoadScenario;
                @SaveGame.started += instance.OnSaveGame;
                @SaveGame.performed += instance.OnSaveGame;
                @SaveGame.canceled += instance.OnSaveGame;
                @Quit.started += instance.OnQuit;
                @Quit.performed += instance.OnQuit;
                @Quit.canceled += instance.OnQuit;
                @AudioMenu.started += instance.OnAudioMenu;
                @AudioMenu.performed += instance.OnAudioMenu;
                @AudioMenu.canceled += instance.OnAudioMenu;
                @NewGame.started += instance.OnNewGame;
                @NewGame.performed += instance.OnNewGame;
                @NewGame.canceled += instance.OnNewGame;
                @CloseMenuOrPopUp.started += instance.OnCloseMenuOrPopUp;
                @CloseMenuOrPopUp.performed += instance.OnCloseMenuOrPopUp;
                @CloseMenuOrPopUp.canceled += instance.OnCloseMenuOrPopUp;
                @Ports.started += instance.OnPorts;
                @Ports.performed += instance.OnPorts;
                @Ports.canceled += instance.OnPorts;
                @Topias.started += instance.OnTopias;
                @Topias.performed += instance.OnTopias;
                @Topias.canceled += instance.OnTopias;
                @GraphView.started += instance.OnGraphView;
                @GraphView.performed += instance.OnGraphView;
                @GraphView.canceled += instance.OnGraphView;
                @ActivateMiscZoning.started += instance.OnActivateMiscZoning;
                @ActivateMiscZoning.performed += instance.OnActivateMiscZoning;
                @ActivateMiscZoning.canceled += instance.OnActivateMiscZoning;
                @ToggleMapView.started += instance.OnToggleMapView;
                @ToggleMapView.performed += instance.OnToggleMapView;
                @ToggleMapView.canceled += instance.OnToggleMapView;
                @Gates.started += instance.OnGates;
                @Gates.performed += instance.OnGates;
                @Gates.canceled += instance.OnGates;
                @ToggleHelpers.started += instance.OnToggleHelpers;
                @ToggleHelpers.performed += instance.OnToggleHelpers;
                @ToggleHelpers.canceled += instance.OnToggleHelpers;
                @SOULView.started += instance.OnSOULView;
                @SOULView.performed += instance.OnSOULView;
                @SOULView.canceled += instance.OnSOULView;
                @ActivateKarmaZoning.started += instance.OnActivateKarmaZoning;
                @ActivateKarmaZoning.performed += instance.OnActivateKarmaZoning;
                @ActivateKarmaZoning.canceled += instance.OnActivateKarmaZoning;
                @ActivateLimboZoning.started += instance.OnActivateLimboZoning;
                @ActivateLimboZoning.performed += instance.OnActivateLimboZoning;
                @ActivateLimboZoning.canceled += instance.OnActivateLimboZoning;
                @MicroView.started += instance.OnMicroView;
                @MicroView.performed += instance.OnMicroView;
                @MicroView.canceled += instance.OnMicroView;
                @TrainingCentres.started += instance.OnTrainingCentres;
                @TrainingCentres.performed += instance.OnTrainingCentres;
                @TrainingCentres.canceled += instance.OnTrainingCentres;
                @ActivateOmniBolgeLoveDomeZoning.started += instance.OnActivateOmniBolgeLoveDomeZoning;
                @ActivateOmniBolgeLoveDomeZoning.performed += instance.OnActivateOmniBolgeLoveDomeZoning;
                @ActivateOmniBolgeLoveDomeZoning.canceled += instance.OnActivateOmniBolgeLoveDomeZoning;
                @TogglePlanetView.started += instance.OnTogglePlanetView;
                @TogglePlanetView.performed += instance.OnTogglePlanetView;
                @TogglePlanetView.canceled += instance.OnTogglePlanetView;
                @Roads.started += instance.OnRoads;
                @Roads.performed += instance.OnRoads;
                @Roads.canceled += instance.OnRoads;
                @SpecialBuildings.started += instance.OnSpecialBuildings;
                @SpecialBuildings.performed += instance.OnSpecialBuildings;
                @SpecialBuildings.canceled += instance.OnSpecialBuildings;
                @KarmaTrack.started += instance.OnKarmaTrack;
                @KarmaTrack.performed += instance.OnKarmaTrack;
                @KarmaTrack.canceled += instance.OnKarmaTrack;
                @ToggleMicroManager.started += instance.OnToggleMicroManager;
                @ToggleMicroManager.performed += instance.OnToggleMicroManager;
                @ToggleMicroManager.canceled += instance.OnToggleMicroManager;
                @NukeButton.started += instance.OnNukeButton;
                @NukeButton.performed += instance.OnNukeButton;
                @NukeButton.canceled += instance.OnNukeButton;
                @ToggleRemoteControl.started += instance.OnToggleRemoteControl;
                @ToggleRemoteControl.performed += instance.OnToggleRemoteControl;
                @ToggleRemoteControl.canceled += instance.OnToggleRemoteControl;
                @TogglePreviousTempo.started += instance.OnTogglePreviousTempo;
                @TogglePreviousTempo.performed += instance.OnTogglePreviousTempo;
                @TogglePreviousTempo.canceled += instance.OnTogglePreviousTempo;
                @GreenZoning.started += instance.OnGreenZoning;
                @GreenZoning.performed += instance.OnGreenZoning;
                @GreenZoning.canceled += instance.OnGreenZoning;
                @YellowZoning.started += instance.OnYellowZoning;
                @YellowZoning.performed += instance.OnYellowZoning;
                @YellowZoning.canceled += instance.OnYellowZoning;
                @OrangeZoning.started += instance.OnOrangeZoning;
                @OrangeZoning.performed += instance.OnOrangeZoning;
                @OrangeZoning.canceled += instance.OnOrangeZoning;
                @BrownZoning.started += instance.OnBrownZoning;
                @BrownZoning.performed += instance.OnBrownZoning;
                @BrownZoning.canceled += instance.OnBrownZoning;
                @PurpleZoning.started += instance.OnPurpleZoning;
                @PurpleZoning.performed += instance.OnPurpleZoning;
                @PurpleZoning.canceled += instance.OnPurpleZoning;
                @RedZoning.started += instance.OnRedZoning;
                @RedZoning.performed += instance.OnRedZoning;
                @RedZoning.canceled += instance.OnRedZoning;
                @BlueZoning.started += instance.OnBlueZoning;
                @BlueZoning.performed += instance.OnBlueZoning;
                @BlueZoning.canceled += instance.OnBlueZoning;
                @GenericZoning.started += instance.OnGenericZoning;
                @GenericZoning.performed += instance.OnGenericZoning;
                @GenericZoning.canceled += instance.OnGenericZoning;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @JumpViewToHeaven.started += instance.OnJumpViewToHeaven;
                @JumpViewToHeaven.performed += instance.OnJumpViewToHeaven;
                @JumpViewToHeaven.canceled += instance.OnJumpViewToHeaven;
                @JumpViewToHell.started += instance.OnJumpViewToHell;
                @JumpViewToHell.performed += instance.OnJumpViewToHell;
                @JumpViewToHell.canceled += instance.OnJumpViewToHell;
                @CenterANDZoomIn.started += instance.OnCenterANDZoomIn;
                @CenterANDZoomIn.performed += instance.OnCenterANDZoomIn;
                @CenterANDZoomIn.canceled += instance.OnCenterANDZoomIn;
                @CenterANDZoomOut.started += instance.OnCenterANDZoomOut;
                @CenterANDZoomOut.performed += instance.OnCenterANDZoomOut;
                @CenterANDZoomOut.canceled += instance.OnCenterANDZoomOut;
                @CentreViewToCursor.started += instance.OnCentreViewToCursor;
                @CentreViewToCursor.performed += instance.OnCentreViewToCursor;
                @CentreViewToCursor.canceled += instance.OnCentreViewToCursor;
            }
        }
    }
    public AfterLifeActionsActions @AfterLifeActions => new AfterLifeActionsActions(this);
    public interface IAfterLifeActionsActions
    {
        void OnMoveView(InputAction.CallbackContext context);
        void OnRotateView(InputAction.CallbackContext context);
        void OnToggleTopDownView(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnLoadGame(InputAction.CallbackContext context);
        void OnLoadScenario(InputAction.CallbackContext context);
        void OnSaveGame(InputAction.CallbackContext context);
        void OnQuit(InputAction.CallbackContext context);
        void OnAudioMenu(InputAction.CallbackContext context);
        void OnNewGame(InputAction.CallbackContext context);
        void OnCloseMenuOrPopUp(InputAction.CallbackContext context);
        void OnPorts(InputAction.CallbackContext context);
        void OnTopias(InputAction.CallbackContext context);
        void OnGraphView(InputAction.CallbackContext context);
        void OnActivateMiscZoning(InputAction.CallbackContext context);
        void OnToggleMapView(InputAction.CallbackContext context);
        void OnGates(InputAction.CallbackContext context);
        void OnToggleHelpers(InputAction.CallbackContext context);
        void OnSOULView(InputAction.CallbackContext context);
        void OnActivateKarmaZoning(InputAction.CallbackContext context);
        void OnActivateLimboZoning(InputAction.CallbackContext context);
        void OnMicroView(InputAction.CallbackContext context);
        void OnTrainingCentres(InputAction.CallbackContext context);
        void OnActivateOmniBolgeLoveDomeZoning(InputAction.CallbackContext context);
        void OnTogglePlanetView(InputAction.CallbackContext context);
        void OnRoads(InputAction.CallbackContext context);
        void OnSpecialBuildings(InputAction.CallbackContext context);
        void OnKarmaTrack(InputAction.CallbackContext context);
        void OnToggleMicroManager(InputAction.CallbackContext context);
        void OnNukeButton(InputAction.CallbackContext context);
        void OnToggleRemoteControl(InputAction.CallbackContext context);
        void OnTogglePreviousTempo(InputAction.CallbackContext context);
        void OnGreenZoning(InputAction.CallbackContext context);
        void OnYellowZoning(InputAction.CallbackContext context);
        void OnOrangeZoning(InputAction.CallbackContext context);
        void OnBrownZoning(InputAction.CallbackContext context);
        void OnPurpleZoning(InputAction.CallbackContext context);
        void OnRedZoning(InputAction.CallbackContext context);
        void OnBlueZoning(InputAction.CallbackContext context);
        void OnGenericZoning(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnJumpViewToHeaven(InputAction.CallbackContext context);
        void OnJumpViewToHell(InputAction.CallbackContext context);
        void OnCenterANDZoomIn(InputAction.CallbackContext context);
        void OnCenterANDZoomOut(InputAction.CallbackContext context);
        void OnCentreViewToCursor(InputAction.CallbackContext context);
    }
}
